### ISSUE TITLE
Assets Do Not Generate

### ISSUE THREAD

**Issue by martindale** [FabricLabs/maki#109]
In some cases, it seems as if assets are not included / do not generate in inherited projects.  See martindale/melody#5 for the specific case.

**Comment by martindale** [comment]
@fractastical I spoke with you over the weekend about a new install you were doing, would love to connect with you and hear about your experience.  We might be able to close this bug!

**Comment by fractastical** [comment]
I'm pretty sure this bug is simply from not having mongodb running.

**Comment by martindale** [comment]
@jnull can you confirm that your brand-new install of Etymog rendered the correct styles?

**Comment by ghost** [comment]
![image](https://cloud.githubusercontent.com/assets/3529087/25035148/9a438dae-20a0-11e7-8a13-a270ff72f13a.png)

![image](https://cloud.githubusercontent.com/assets/3529087/25035157/acf8fbfa-20a0-11e7-93d4-df0c2a5eb2e2.png)

**Comment by martindale** [comment]
Awesome!  Thank you so much!
