### ISSUE TITLE
README install uses wrong port number (27017)

### ISSUE THREAD

**Issue by fractastical** [FabricLabs/maki#140]
Tried to run default install. I get this. 

> { [Error: Cannot find module '../build/Release/bson'] code: 'MODULE_NOT_FOUND' }
> js-bson: Failed to load c++ bson extension, using pure JS version
> [WARNING] Resource "Widget" attribute `name` has no type. You should consider adding one.
> INTERNAL ERROR [Error: failed to connect to [localhost:27017]]
>

**Comment by martindale** [comment]
This is because MongoDB is not running; should work once the database runs.
